name: Bradford Chalmers
favicon: null
layout_spectrum: 0.6365938638336957
typography_spectrum: 0.2887417911551893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.08244243822991848
  lightness: 0.28696526028215885
  saturation: 0.5843557866755873
  rhythmicContrast: 0.9182687909342349
purpose: []
